# Exemple de fichier de clés API (à copier en keys.py et à compléter en local)
STEAM_API_KEY = "VOTRE_CLE_STEAM"
RAWG_API_KEY = "VOTRE_CLE_RAWG"
GEMINI_API_KEY_VAL = "VOTRE_CLE_GEMINI_VAL"
GEMINI_API_KEY_YANN = "VOTRE_CLE_GEMINI_YANN"
GEMINI_API_KEY_ALEX = "VOTRE_CLE_GEMINI_ALEX"
GEMINI_API_KEY = GEMINI_API_KEY_VAL  # ou _YANN, _ALEX 